"""add_event_id_and_nullable_health

Revision ID: becd5d6ea3f2
Revises: 9b3154de6499
Create Date: 2026-09-27 11:45:54.486980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'becd5d6ea3f2'
down_revision: Union[str, None] = '9b3154de6499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('event_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_measurement_event_id'), 'measurement', ['event_id'], unique=True)
    op.alter_column('sensor_health', 'measurement_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor_health', 'measurement_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_measurement_event_id'), table_name='measurement')
    op.drop_column('measurement', 'event_id')
    # ### end Alembic commands ###
